// src/routes/projects/Projects.svelte
<script lang="ts">
	import Markdown from '$lib/components/Markdown.svelte';
	import type { Post } from '$lib/types';
	import { formatTime } from '$lib/utils';

	export let data: Post;
	export let images: Record<string, { default: string }>;

	function isURL(path: string): boolean {
		try {
			new URL(path);
			return true;
		} catch {
			return false;
		}
	}
</script>

<!-- project header -->
<h3 class="text-stone-100 text-xl md:text-2xl font-semibold mb-4 flex flex-wrap items-center">
	{#if data.title}
		<span class="mr-2">{data.title}</span>
	{/if}
	{#if data.date}
		<small class="text-stone-400 text-base font-normal">
			{formatTime('%d %B %Y', data.date)}
		</small>
	{/if}
</h3>

<!-- project body -->
<div class="grid md:grid-cols-3 gap-6 items-start">
	<!-- main image -->
	{#if data.image}
		<div class="md:col-span-1">
			<a
				rel="external"
				href={isURL(data.image) ? data.image : images[`../../projects/${data.image}`]?.default}
			>
				<img
					src={isURL(data.image) ? data.image : images[`../../projects/${data.image}`]?.default}
					alt="{data.title} preview image"
					class="rounded-lg shadow-sm max-h-64 object-cover w-full"
				/>
			</a>
		</div>
	{/if}

	<!-- description -->
	<div
		class="md:col-span-2 prose prose-stone prose-invert prose-headings:font-semibold prose-a:text-blue-600 hover:prose-a:text-blue-800 max-w-none"
	>
		<Markdown source={data.content} />
	</div>
</div>

<!-- subimages -->
{#if data.subimages}
	<div class="grid grid-cols-2 md:grid-cols-3 gap-4 mt-6">
		{#each data.subimages as image}
			<a rel="external" href={isURL(image) ? image : images[`../../projects/${image}`]?.default}>
				<img
					src={isURL(image) ? image : images[`../../projects/${image}`]?.default}
					alt="{data.title} subimage"
					class="rounded-lg shadow-sm object-cover w-full max-h-48"
				/>
			</a>
		{/each}
	</div>
{/if}

<style lang="postcss">
	@reference "tailwindcss";

	h3 {
		@apply break-words;
	}
</style>

// src/pages/Projects.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import Seo from '../lib/components/Seo';
import { formatTime } from '../lib/utils';

const projects = import.meta.glob('../projects/*.md', {
	eager: true
}) as any;

const images = import.meta.glob('../projects/*.{png,jpg,svg}', {
	eager: true
}) as any;

function getSlug(id: string) {
	return id.match(/\.\.\/projects\/(.*)\.md$/)?.[1];
}

function isURL(path: string): boolean {
	try {
		new URL(path);
		return true;
	} catch {
		return false;
	}
}

function getImageUrl(path: string) {
	if (!path) return null;
	if (isURL(path)) return path;
	return images[`../projects/${path}`]?.default;
}

const Projects: React.FC = () => {
	const sortedProjectIds = Object.keys(projects).sort((a, b) => {
		const projA = projects[a].default || projects[a];
		const projB = projects[b].default || projects[b];
		const dateA = new Date(projA.date).getTime();
		const dateB = new Date(projB.date).getTime();
		return dateB - dateA;
	});

	return (
		<>
			<Seo title="Sagnik Chatterjee - Projects" description="my side projects" />

			<section className="layout-md">
				<p className="text-sm md:text-lg mb-4">
					<em> an index of some of my open source projects</em>
				</p>
				<hr className="border-stone-800" />
			</section>

			<div className="layout-md mt-10">
				<div className="grid gap-8">
					{sortedProjectIds.map((id) => {
						const project = projects[id].default || projects[id];
						const slug = getSlug(id);
						return (
							<Link
								key={id}
								to={`/project/${slug}`}
								className="group block p-6 border border-stone-800 rounded-xl hover:bg-stone-900 transition-all duration-200"
							>
								<div className="flex flex-col md:flex-row gap-6">
									{project.image && (
										<div className="w-full md:w-48 h-32 flex-shrink-0">
											<img
												src={getImageUrl(project.image)}
												alt={project.title}
												className="w-full h-full object-cover rounded-lg grayscale group-hover:grayscale-0 transition-all duration-500"
											/>
										</div>
									)}
									<div className="flex-grow">
										<div className="flex justify-between items-start mb-2">
											<h2 className="text-xl font-semibold text-stone-100 group-hover:text-blue-400 transition-colors">
												{project.title}
											</h2>
											{project.date && (
												<span className="text-stone-500 text-sm">
													{formatTime('%Y', project.date)}
												</span>
											)}
										</div>
										<p className="text-stone-400 line-clamp-2">
											{project.lead || 'Click to view project details...'}
										</p>
										<div className="mt-4 flex flex-wrap gap-2">
											{project.topics &&
												project.topics.map((topic: string) => (
													<span key={topic} className="px-2 py-1 text-xs bg-stone-800 text-stone-300 rounded">
														{topic}
													</span>
												))}
										</div>
									</div>
								</div>
							</Link>
						);
					})}
				</div>
			</div>
		</>
	);
};

export default Projects;
