// src/lib/components/Seo.svelte
<script lang="ts">
	export let title: string;
	export let ogTitle: string | null = null;
	export let description: string;
</script>

<svelte:head>
	<title>{title}</title>
	<meta name="description" content={description} />
	<meta property="og:title" content={ogTitle ?? title} />
	<meta property="og:description" content={description} />
	<meta property="og:image" content="https://sagnikc395.github.io/assets/images/profile.jpeg" />
	<meta name="twitter:card" content="summary_large_image" />
</svelte:head>

// src/lib/components/Seo.tsx
import React from "react";
import { Helmet } from "react-helmet-async";

interface SeoProps {
  title: string;
  ogTitle?: string | null;
  description: string;
}

const Seo: React.FC<SeoProps> = ({ title, ogTitle, description }) => {
  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      <meta property="og:title" content={ogTitle ?? title} />
      <meta property="og:description" content={description} />
      <meta
        property="og:image"
        content="https://sagnikc395.github.io/assets/images/profile.jpeg"
      />
      <meta name="twitter:card" content="summary_large_image" />
    </Helmet>
  );
};

export default Seo;
